name: C++ Build and Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
     workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile program
      run: |
        ls -la
        g++ -std=c++17 -pthread main.cpp -o call-center
        ls -la  # confirm binary exists

    - name: Run program
      run: ./call-center
